### ISSUE TITLE
GeoIP cannot be downloaded during tests

### ISSUE THREAD

**Issue by leplatrem** [mozilla/classify-client#101]
` Could not resolve host: geolite.maxmind.com`

**Comment by sciurus** [comment]
I believe this is expected due to https://blog.maxmind.com/2019/12/18/significant-changes-to-accessing-and-using-geolite2-databases/

This was discussed at the time @mythmon and others, but I do not remember what if any decisions were made.

**Comment by leplatrem** [comment]
Now solved 😅
