### ISSUE TITLE
Upgrade actix-web to 3.0

### ISSUE THREAD

**Issue by sciurus** [mozilla/classify-client#102]
https://paper.dropbox.com/published/Announcing-Actix-Web-v3.0-QOXXb1lXgTubzXHzUq9ONY5

**Comment by mythmon** [comment]
I'm happy to see that Actix is continuing on, and I definitely plan to use it in the future. On the other hand, I don't see any compelling reasons to make changes to classify-client. It seems that the 3.0 version primarily improves stability, and classify-client has (to my knowledge) been as stable as we need it to be. Does that sound correct @sciurus?

**Comment by leplatrem** [comment]
Fixed by https://github.com/mozilla/classify-client/pull/123
