### ISSUE TITLE
Remove use of ci-docker-bases

### ISSUE THREAD

**Issue by ddurst** [mozilla/classify-client#121]
We want to retire ci-docker-bases. In order to do so, all projects using it must migrate their use to something else. Classify-client is one of those projects.

Progress and notes can be found in the [decision brief](https://docs.google.com/document/d/1xW6SANLXmh4pPDeyU7Zenim-XXteXzNyy1tYeWIN6pg/edit#heading=h.gmdpfifmxyyd).

**Comment by jwhitlock** [comment]
🕘 We plan to stop updates to the `mozilla/cidockerbases` `docker` and `rust` images on October 1, 2022, less than 3 months away. This project uses this image in CircleCI. See https://github.com/mozilla/ci-docker-bases/issues/322 for examples of projects that have successfully migrated away from `mozilla/cidockerbases`
