### ISSUE TITLE
Add Instrumentation

### ISSUE THREAD

**Issue by sciurus** [mozilla/classify-client#41]
We should have some instrumentation so we can know what classify client is doing. For the rationale behind these suggestions, see [The First Four Things You Measure](https://www.honeycomb.io/blog/instrumentation-the-first-four-things-you-measure/).

I think at a minimum we want timer to track the number and latency of successful and failed responses. Something like the name `classify-client.response` tagged either `status:success` or `status:error`?

Since classify-client is asynchronous and can be handling multiple requests at once, it would be nice to have a gauge that is incremented when a request is received and decremented when we've finished sending the response. Something like the name `classify-client.ongoing_requests`?

Finally, it could be interesting to have a counter that is incremented for each successful request and labeled by the country of the client. Something like the name `classify-client.location` with tags like `country:us`, `country:fr`, etc?

To add the instrumentation, [cadence](https://github.com/tshlabs/cadence) is the most promising crate I can find. It supports statsd metric types along with the dogstatsd extension for tags and an efficient method of publishing them.

The host and port to send to should be configurable by environment variables and default to localhost. and 8125.

**Comment by mythmon** [comment]
This sounds like a good idea. I've started working on this with cadence. I have a couple questions.

I thought request timing was a part of Dockerflow logging, but I don't see it there. Should it be there? Should it be in both?

For `classify-client.ongoing_requests`, a statsd gauge seems to be a value we set, which sounds tricky to implement. Would it be ok to use a counter instead? We would increment it when the request starts and decrement it when the request ends. That would be much easier to implement.

**Comment by sciurus** [comment]
We don't get any metrics out of our logging without extra work. It's better for the application to generate them directly.

We do get response times from load balancer and nginx (if it's present) logs, but these don't accurately reflect time the application spent due to network delays and (potentially) queuing.

Since this is statsd, a counter that you increment and decrement should work fine. My head was in prometheus-land when I mentioned gauge; counters are only for monotonically increasing values there.
