### ISSUE TITLE
Push docker images to dockerhub for deployment

### ISSUE THREAD

**Issue by mythmon** [mozilla/classify-client#7]
We should figure out what strategy we want to use for deploying the project. This might involve building Docker images in CI and pushing them to the Google image registry.

**Comment by mythmon** [comment]
@sciurus do you think we should go with a workflow similar to how Normandy works? Auto-deploy master to dev, auto deploy tags to stage, and manually deploy stage to prod? Or do you want to do something different?

Also, can you set up a Dockerhub target we can push to, and set up Circle with the credentials we'd need?

**Comment by sciurus** [comment]
Yes, we should keep the deployment process identical to the rest of normandy.

I can set up Circle and Dockerhub.

**Comment by sciurus** [comment]
The Circle CI job now has the standard environment variables set up so that it can push to https://hub.docker.com/r/mozilla/classify-client

**Comment by mythmon** [comment]
The merge of this PR successfully deployed a `latest` branch on Dockerhub :tada:
