### ISSUE TITLE
Release v1.0.0

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/classify-client#70]
Welcome Release Captain ⛵

- [x] Create 1.1.0 Milestone (due date two weeks from now)
- [x] Move all open tickets in 1.0.0 to 1.1.0
- [x] Close 1.0.0 Milestone
- [x] Approve and merge all open dependabot PRs
- [x] Pull master
- [x] Ensure `cargo test` passes
- [x] `git tag v1.0.0; git push --tags`
- [x] `@here deploying classify client v1.0.0 to stage https://github.com/mozilla/classify-client/milestone/1?closed=1` in #normandy
- [x] Quickly verify that stage loads with v1.0.0
- [x] `@bpitts please push classify-client v1.0.0 to production` in #normandy
- [x] Verify that prod loads with v1.0.0
- [ ] Create release issue for Release v1.1.0

**Comment by leplatrem** [comment]
@jaredkerim This seems to be done :) 

We fixed a couple of things in the last weeks (including heartbeat), shall we release 1.1.0? Please let me know if I can help :)

**Comment by leplatrem** [comment]
v1.1.0 and v1.1.1 exist already https://github.com/mozilla/classify-client/tags
